AnimeCollection/Models/Anime.cs
using AnimeCollection.Data.Enum;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AnimeCollection.Models
{
    public class Anime
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        public string PosterImage { get; set; }
        [Required]
        public string Description { get; set; }
        public AnimeStatus Status { get; set; }
        public int Episodes { get; set; }
        public string Studio { get; set; }
        public DateTime DateAired { get; set; }

        [ForeignKey("GenreId")]
        public ICollection<AnimeGenre> AnimeGenres { get; set; }

    }
}

AnimeCollection/Models/AnimeGenre.cs
using System.ComponentModel.DataAnnotations;

namespace AnimeCollection.Models
{
	public class AnimeGenre
	{
		[Key]
		public int Id { get; set; }
		public int AnimeId { get; set; }
		public Anime Anime { get; set; }

		public int GenreId { get; set; }
		public Genre Genre { get; set; }
	}
}

AnimeCollection/Controllers/AnimeController.cs
using AnimeCollection.Data;
using AnimeCollection.Interfaces;
using AnimeCollection.Models;
using AnimeCollection.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace AnimeCollection.Controllers
{
    public class AnimeController : Controller
    {
        private readonly IAnimeRepository _animeRepository;
        private readonly IGenreRepository _genreRepository;
        private readonly IPhotoService _photoService;

        public AnimeController(IAnimeRepository animeRepository, IGenreRepository genreRepository, IPhotoService photoService)
        {
            _animeRepository = animeRepository;
            _genreRepository = genreRepository;
            _photoService = photoService;
        }
       /* public async Task<IActionResult> Index()
        {
            IEnumerable<Anime> anime = await _animeRepository.GetAnimes();
            return View(anime);
        }  */

        public async Task<IActionResult> Detail(int id)
        {
            Anime anime = await _animeRepository.GetAnimeById(id);
            IEnumerable<Genre> genres = await _animeRepository.GetGenresForAnime(id);

            // Pass anime and genres to the view
            ViewData["Genres"] = genres;

            return View(anime);
        }

        public IActionResult Create()
        {
            ViewBag.Genres = _genreRepository.GetGenres().Result; // Assuming GetGenres() returns Task<IEnumerable<Genre>>
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateAnimeViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var result = await _photoService.AddPhotoAsync(viewModel.PosterImage);
                // Map properties from view model to Anime entity
                var anime = new Anime
                {
                    Title = viewModel.Title,
                    PosterImage = result.Url.ToString(),
                    Description = viewModel.Description,
                    Status = viewModel.Status,
                    Episodes = viewModel.Episodes,
                    Studio = viewModel.Studio,
                    DateAired = viewModel.DateAired
                };

                _animeRepository.Add(anime);

                return RedirectToAction(nameof(Index));
            }
            else
            {
                // Handle upload failure
                ModelState.AddModelError("", "Failed to upload photo.");
            }
            return View(viewModel);

        }

        public async Task<IActionResult> AnimeGenre()
        {
            IEnumerable<Genre> genre = await _genreRepository.GetGenres();
            return View(genre);
        }

        [HttpGet]
        public async Task<IActionResult> AnimeGenre(int id)
        {
            var anime = await _animeRepository.GetAnimeById(id);
            ViewBag.Genres = await _genreRepository.GetGenres();
            return View("AnimeGenre", anime);
        }

        [HttpPost]
        public async Task<IActionResult> AnimeGenre(int animeId, int[] selectedGenres)
        {
            if (selectedGenres != null)
            {
                foreach (var genreId in selectedGenres)
                {
                    await _animeRepository.AddGenreToAnime(animeId, genreId);
                }
            }
            return RedirectToAction(nameof(Detail), new { id = animeId });
        }

        [HttpPost]
        public async Task<IActionResult> RemoveGenresFromAnime(int animeId, int[] selectedGenres)
        {
            if (selectedGenres != null)
            {
                foreach (var genreId in selectedGenres)
                {
                    await _animeRepository.RemoveGenreFromAnime(animeId, genreId);
                }
            }
            return RedirectToAction(nameof(Detail), new { id = animeId });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            // Retrieve the anime by its ID
            var anime = await _animeRepository.GetAnimeById(id);

            // If the anime exists, delete it
            if (anime != null)
            {
                // Delete the anime and its associated genres
                _animeRepository.Delete(anime);

                await _photoService.DeletePhotoAsync(anime.PosterImage);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                // Anime not found
                return NotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditAnimeViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var result = await _photoService.AddPhotoAsync(viewModel.PosterImage);

                var anime = new Anime
                {
                    Id = viewModel.Id,
                    Title = viewModel.Title,
                    Description = viewModel.Description,
                    PosterImage = result.Url.ToString(),
                    Studio = viewModel.Studio,
                    Episodes = viewModel.Episodes,
                    DateAired = viewModel.DateAired,
                    Status = viewModel.Status
                };

                 _animeRepository.Update(anime);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ModelState.AddModelError("", "Failed to upload photo.");
            }

            return View(viewModel);
        }

        public async Task<IActionResult> Edit(int id)
        {
            Anime anime = await _animeRepository.GetAnimeById(id);
            return View(anime);
        }

        public async Task<IActionResult> Index(string searchString)
        {
            ViewData["CurrentFilter"] = searchString;

            IEnumerable<Anime> anime;

            if (!String.IsNullOrEmpty(searchString))
            {
                anime = await _animeRepository.GetAnimesSearch(searchString);
            }
            else
            {
                anime = await _animeRepository.GetAnimes();
            }

            return View(anime);
        }
    }
}

AnimeCollection/Views/Anime/AnimeGenre.cshtml
@model AnimeCollection.Models.Anime
@using AnimeCollection.Models

@{
    ViewData["Title"] = "Add Genre/s to Anime";
}

<h1>Add Genre/s to @Model.Title</h1>

<form asp-action="AnimeGenre" asp-controller="Anime" method="post">
    @foreach (var genre in ViewBag.Genres as IEnumerable<Genre>)
    {
        // Check if the genre is already associated with the anime
        if (!Model.AnimeGenres.Any(ag => ag.GenreId == genre.Id))
        {
            <div class="form-check">
                <input class="form-check-input" type="checkbox" id="genre-@genre.Id" name="selectedGenres" value="@genre.Id">
                <label class="form-check-label" for="genre-@genre.Id">@genre.Name</label>
            </div>
        }
    }
    <input type="hidden" name="animeId" value="@Model.Id" />
    <button type="submit" class="btn btn-primary mt-3">Save Selected Genres</button>
</form>

   

AnimeCollection/Views/Anime/Create.cshtml
@using AnimeCollection.Data.Enum
@using AnimeCollection.ViewModels
@model CreateAnimeViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form asp-action="Create" method="post" class="row g-3" enctype="multipart/form-data">
    <h1 class="text-center text-primary">Add Anime</h1>
    <div class="col-12">
        <label asp-for="Title" class="form-label">Title</label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="col-12">
        <label asp-for="Description" class="form-label">Description/Synopsis</label>
        <textarea asp-for="Description" class="form-control" rows="3"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="col-12">
        <label asp-for="Studio" class="form-label">Studio</label>
        <input asp-for="Studio" class="form-control" />
        <span asp-validation-for="Studio" class="text-danger"></span>
    </div>
    <div class="col-12">
        <label asp-for="Episodes" class="form-label">Number of Episodes</label>
        <input asp-for="Episodes" class="form-control" />
        <span asp-validation-for="Episodes" class="text-danger"></span>
    </div>
    <div class="col-md-4">
        <label asp-for="DateAired" class="form-label">Date Aired</label>
        <input asp-for="DateAired" class="form-control" type="date" />
        <span asp-validation-for="DateAired" class="text-danger"></span>
    </div>
    <div class="col-md-4">
        <label asp-for="Status" class="form-label">Status</label>
        <select asp-for="Status" class="form-select" asp-items="@Html.GetEnumSelectList<AnimeStatus>()">
        </select>
        <span asp-validation-for="Status" class="text-danger"></span>
    </div>
    <div class="col-md-2">
        <div class="d-flex flex-column">
            <label class="form-label">Upload Anime Picture</label>
            <input type="file" name="PosterImage" class="form-control-file" />
            <span asp-validation-for="PosterImage" class="text-danger"></span>
        </div>
    </div>
    <div class="col-12">
        <button type="submit" class="btn btn-primary">Create</button>
    </div>
</form>

AnimeCollection/Views/Anime/Detail.cshtml
@model Anime

@{
    // Retrieve genres from ViewData
    var genres = ViewData["Genres"] as IEnumerable<Genre>;
}

<div class="main-container">
    <nav aria-label="breadcrumb" role="navigation" class="bg-primary text-white">
        <div class="container">
            <!--end of row-->
        </div>
        <!--end of container-->
    </nav>
    <section class="bg-white space-sm">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 mb-4 mb-sm-0">
                    <img alt="Image" src="@Model.PosterImage" class="rounded img-fluid" />
                </div>
                <!--end of col-->
                <div class="col-lg-4 d-flex flex-column justify-content-between mr-auto ml-auto">
                    <div>
                        <h1 class="mb-2">@Model.Title</h1>
                        <a class="btn btn-secondary my-2" asp-area="" asp-controller="Anime" asp-action="AnimeGenre" asp-route-id="@Model.Id">Add genre/s to this anime</a>
                        <!-- List of details -->
                        <ul class="list-group">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Number of Episodes
                                <span>@Model.Episodes</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Studio
                                <span>@Model.Studio</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Status
                                <span>@Model.Status</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Date Aired
                                <span>@Model.DateAired.ToString("yyyy-MM-dd")</span>
                            </li>
                            <!-- Add more list items as needed -->
                        </ul>
                        <h5>Genre/s</h5>
                        <div class="card-columns">
                            @if (genres != null && genres.Any())
                            {
                                @foreach (var genre in genres)
                                {
                                    <div class="card border-light">
                                        <div class="card-body p-2 d-flex justify-content-between align-items-center">
                                            <h6 class="card-title m-0">@genre.Name</h6>
                                            <form method="post" asp-action="RemoveGenresFromAnime" asp-route-animeId="@Model.Id" class="m-0">
                                                <input type="hidden" name="selectedGenres[]" value="@genre.Id" />
                                                <button type="submit" class="btn btn-outline-danger btn-sm">
                                                    Remove
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                }
                            }
                            else
                            {
                                <div class="card border-light">
                                    <div class="card-body p-2">
                                        <p class="card-text m-0">No genres associated with this anime</p>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!--end of col-->
</div>
<!--end of row-->
        </div>
<!--end of container-->
      </section>
<!--end of section-->
<section class="space-sm">
    <div class="container">
        <div class="row justify-content-between">
            <div class="col-12 col-md-8 col-lg-7">
                <h5 class="mb-4">Overview</h5>
                <p class="text-justify" style="max-width: 500px;">
                    @Model.Description
                </p>
                <form method="post" asp-action="Delete" asp-route-id="@Model.Id">
                    @Html.AntiForgeryToken()
                    <button type="submit" class="btn btn-danger mt-4 mb-1">
                        Delete Anime
                    </button>
                </form>
            </div>

        </div>
        <!--end of col-->

    </div>
    <!--end of row-->
    </div>
    <!--end of container-->
</section>

AnimeCollection/Views/Anime/Edit.cshtml
@using AnimeCollection.Data.Enum
@using AnimeCollection.ViewModels
@model Anime
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form asp-action="Edit" method="post" class="row g-3" enctype="multipart/form-data">
    <h1 class="text-center text-primary">Edit Anime</h1>
    <input type="hidden" asp-for="Id" />

    <div class="col-12">
        <label asp-for="Title" class="form-label">Title</label>
        <input asp-for="Title" class="form-control" placeholder="@Model.Title" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>

    <div class="col-12">
        <label asp-for="Description" class="form-label">Description/Synopsis</label>
        <textarea asp-for="Description" class="form-control" rows="3" placeholder="@Model.Description"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="col-12">
        <label asp-for="Studio" class="form-label">Studio</label>
        <input asp-for="Studio" class="form-control" placeholder="@Model.Studio" />
        <span asp-validation-for="Studio" class="text-danger"></span>
    </div>

    <div class="col-12">
        <label asp-for="Episodes" class="form-label">Number of Episodes</label>
        <input asp-for="Episodes" class="form-control" placeholder="@Model.Episodes" />
        <span asp-validation-for="Episodes" class="text-danger"></span>
    </div>

    <div class="col-md-4">
        <label asp-for="DateAired" class="form-label">Date Aired</label>
        <input asp-for="DateAired" class="form-control" type="date" placeholder="@Model.DateAired.ToString("yyyy-MM-dd")" />
        <span asp-validation-for="DateAired" class="text-danger"></span>
    </div>

    <div class="col-md-4">
        <label asp-for="Status" class="form-label">Status</label>
        <select asp-for="Status" class="form-select" asp-items="@Html.GetEnumSelectList<AnimeStatus>()">
            @*<option value="@Model.Status" selected>@Model.Status</option>*@
        </select>
        <span asp-validation-for="Status" class="text-danger"></span>
    </div>

    <div class="col-md-2">
        <div class="d-flex flex-column">
            <label class="form-label">Upload Anime Picture</label>
            <input type="file" name="PosterImage" class="form-control-file" />
            <span asp-validation-for="PosterImage" class="text-danger"></span>
        </div>
    </div>

    <div class="col-12">
        <button type="submit" class="btn btn-primary">Update</button>
    </div>
</form>

AnimeCollection/Views/Anime/Index.cshtml
@model IEnumerable<Anime>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<div class="album py-5 bg-light">
    <div class="container">
        <form asp-controller="Anime" asp-action="Index" method="get" class="mb-2">
            <div class="input-group">
                <input type="text" name="searchString" class="form-control" placeholder="Search by Title" value="@ViewBag.CurrentFilter">
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </form>
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="@item.PosterImage" alt="@item.Title">
                        <div class="card-body">
                            <h4 class="card-title fw-bold text-center">@item.Title</h4>
                            <p class="card-text"><strong>Episode/s:</strong> @item.Episodes</p>
                            <p class="card-text"><strong>Status:</strong> @item.Status</p>
                            <p class="card-text"><strong>Date Aired:</strong> @item.DateAired.ToString("yyyy-MM-dd")</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a asp-controller="Anime" asp-action="Detail" asp-route-id="@item.Id" type="button" class="btn btn-sm btn-outline-secondary">View</a>
                                    <a asp-controller="Anime" asp-action="Edit" asp-route-id="@item.Id" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</div>